name: 'Checkout Lint Build Test'
description: 'Checks out the sources, executes the linting, builds and tests the sources'
runs:
  using: "composite"
  steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Install
        run: npm install
      - name: Lint
        run: npm run lint 
      - name: Build
        run: npm run pack
