name: PagerDuty Helper GitHub Actions
on: [push]
jobs:
    lint-build-test:
        runs-on: ubuntu-latest
        steps:
            - id: checkout-lint-build-test
              uses: ./github/actions/checkout-lint-build-test.yml
